### PR TITLE
update @poppinss/utils

### PR DESCRIPTION
**Pull request by TiBianMod**
related to your commit: https://github.com/poppinss/utils/commit/557dabb89f658638e777c328238d425ab2094412

### CODE REVIEW

**Comment by Julien-R44** [comment]
Thanks !

**Comment by Julien-R44** [comment]
okay, i will make a new release

just out of curiosity: in what environment are you using bentocache?

**Comment by TiBianMod** [comment]
`nodejs (adonisjs)` and `bun (private)`

**Comment by Julien-R44** [comment]
not sure why you had the error then. was Bun throwing you an error about @poppinss/utils?

Released with `bentocache@1.0.0-beta.7`

**Comment by TiBianMod** [comment]
hehe, I was playing around with `Vite` to bundle some packages (lib mode), and I discovered the issue

**Pull request merged**
